// TradeVault service worker.
// Cache-first, offline-first. No remote origins are ever contacted —
// every request this worker serves comes from this same local bundle.

const VERSION = 'tradevault-v1'
const CORE_ASSETS = ['./', './index.html', './manifest.json', './offline.html']

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(VERSION)
      // Always cache the core shell first.
      await cache.addAll(CORE_ASSETS).catch(() => {})
      // Then cache every hashed build asset listed in the manifest
      // generated by scripts/generate-precache.mjs at build time.
      try {
        const res = await fetch('./precache-manifest.json')
        if (res.ok) {
          const { files } = await res.json()
          await Promise.all(
            files.map((f) => cache.add(f).catch(() => {}))
          )
        }
      } catch {
        // No manifest yet (e.g. during `vite dev`) — that's fine.
      }
      self.skipWaiting()
    })()
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys()
      await Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)))
      await self.clients.claim()
    })()
  )
})

self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET') return

  event.respondWith(
    (async () => {
      const cache = await caches.open(VERSION)
      const cached = await cache.match(request)
      if (cached) return cached

      try {
        const fresh = await fetch(request)
        if (fresh && fresh.ok) cache.put(request, fresh.clone())
        return fresh
      } catch {
        if (request.mode === 'navigate') {
          return (await cache.match('./index.html')) || (await cache.match('./offline.html'))
        }
        return new Response('', { status: 504, statusText: 'Offline' })
      }
    })()
  )
})
